'use strict';
const chars = {
	"Albedo": {
		"rarity": 5,
		"weapon": "Sword",
		"region": "Mondstadt",
		"type": "Geo",
		"gem": "Prithiva Topaz",
		"boss": "Basalt Pillar",
		"local": "Cecilia",
		"common": "samachurl",
		"books": "Ballad",
		"weeklyBoss": "Tusk of Monoceros Caeli",
		"conBonus": {"2":3,"3":5}
	},
	"Alhaitham": {
		"rarity": 5,
		"weapon": "Sword",
		"region": "Sumeru",
		"type": "Dendro",
		"gem": "Nagadus Emerald",
		"boss": "Pseudo-Stamens",
		"local": "Sand Grease Pupa",
		"common": "eremites",
		"books": "Ingenuity",
		"weeklyBoss": "Mirror of Mushin",
		"conBonus": {"2":3,"3":5}
	},
	"Aloy": {
		"hasCons": false,
		"rarity": 5,
		"vision": "Aloy",
		"weapon": "Bow",
		"region": null,
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Crystalline Bloom",
		"local": "Crystal Marrow",
		"common": "specter",
		"books": "Freedom",
		"weeklyBoss": "Molten Moment"
	},
	"Amber": {
		"rarity": 4,
		"weapon": "Bow",
		"region": "Mondstadt",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Everflame Seed",
		"local": "Small Lamp Grass",
		"common": "hilichurlShooter",
		"books": "Freedom",
		"weeklyBoss": "Dvalin's Sigh",
		"conBonus": {"3":3,"2":5}
	},
	"Arataki Itto": {
		"rarity": 5,
		"weapon": "Claymore",
		"region": "Inazuma",
		"type": "Geo",
		"gem": "Prithiva Topaz",
		"boss": "Riftborn Regalia",
		"local": "Onikabuto",
		"common": "slime",
		"books": "Elegance",
		"weeklyBoss": "Ashen Heart",
		"conBonus": {"2":3,"3":5}
	},
	"Arlecchino": {
		"include": false,
		"rarity": 5,
		"weapon": "Polearm",
		"region": "Snezhnaya",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": null,
		"local": null,
		"common": null,
		"books": null,
		"weeklyBoss": null,
		"conBonus": null
	},
	"Baizhu": {
		"rarity": 5,
		"weapon": "Catalyst",
		"region": "Liyue",
		"type": "Dendro",
		"gem": "Nagadus Emerald",
		"boss": "Evergloom Ring",
		"local": "Violetgrass",
		"common": "fungus",
		"books": "Gold",
		"weeklyBoss": "Worldspan Fern",
		"conBonus": {"3":3,"2":5}
	},
	"Barbara": {
		"rarity": 4,
		"weapon": "Catalyst",
		"region": "Mondstadt",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Cleansing Heart",
		"local": "Philanemo Mushroom",
		"common": "samachurl",
		"books": "Freedom",
		"weeklyBoss": "Ring of Boreas",
		"conBonus": {"3":3,"2":5}
	},
	"Beidou": {
		"rarity": 4,
		"weapon": "Claymore",
		"region": "Liyue",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Lightning Prism",
		"local": "Noctilucous Jade",
		"common": "treasureHoarder",
		"books": "Gold",
		"weeklyBoss": "Dvalin's Sigh",
		"conBonus": {"2":3,"3":5}
	},
	"Bennett": {
		"rarity": 4,
		"weapon": "Sword",
		"region": "Mondstadt",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Everflame Seed",
		"local": "Windwheel Aster",
		"common": "treasureHoarder",
		"books": "Resistance",
		"weeklyBoss": "Dvalin's Plume",
		"conBonus": {"2":3,"3":5}
	},
	"Candace": {
		"rarity": 4,
		"weapon": "Polearm",
		"region": "Sumeru",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Light Guiding Tetrahedron",
		"local": "Henna Berry",
		"common": "eremites",
		"books": "Admonition",
		"weeklyBoss": "Tears of the Calamitous God",
		"conBonus": {"3":3,"2":5}
	},
	"Charlotte": {
		"rarity": 4,
		"weapon": "Catalyst",
		"region": "Fontaine",
		"visionType": "Ousia",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Tourbillon Device",
		"local": "Beryl Conch",
		"common": "clockworkMeka",
		"books": "Justice",
		"weeklyBoss": "Lightless Silk String",
		"conBonus": {"3":3,"2":5}
	},
	"Chevreuse": {
		"include": false,
		"rarity": 4,
		"weapon": "Polearm",
		"region": "Fontaine",
		"visionType": "Ousia",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": null,
		"local": null,
		"common": null,
		"books": null,
		"weeklyBoss": null,
		"conBonus": null
	},
	"Chongyun": {
		"rarity": 4,
		"weapon": "Claymore",
		"region": "Liyue",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Hoarfrost Core",
		"local": "Cor Lapis",
		"common": "hilichurl",
		"books": "Diligence",
		"weeklyBoss": "Dvalin's Sigh",
		"conBonus": {"3":3,"2":5}
	},
	"Clorinde": {
		"include": false,
		"rarity": 5,
		"weapon": "Sword",
		"region": "Fontaine",
		"visionType": "Pneuma",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": null,
		"local": null,
		"common": null,
		"books": null,
		"weeklyBoss": null,
		"conBonus": null
	},
	"Collei": {
		"rarity": 4,
		"weapon": "Bow",
		"region": "Sumeru",
		"type": "Dendro",
		"gem": "Nagadus Emerald",
		"boss": "Majestic Hooked Beak",
		"local": "Rukkhashava Mushrooms",
		"common": "hilichurlShooter",
		"books": "Praxis",
		"weeklyBoss": "Tears of the Calamitous God",
		"conBonus": {"2":3,"3":5}
	},
	"Cyno": {
		"rarity": 5,
		"weapon": "Polearm",
		"region": "Sumeru",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Thunderclap Fruitcore",
		"local": "Scarab",
		"common": "samachurl",
		"books": "Admonition",
		"weeklyBoss": "Mudra of the Malefic General",
		"conBonus": {"3":3,"2":5}
	},
	"Dehya": {
		"rarity": 5,
		"weapon": "Claymore",
		"region": "Sumeru",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Light Guiding Tetrahedron",
		"local": "Sand Grease Pupa",
		"common": "eremites",
		"books": "Praxis",
		"weeklyBoss": "Puppet Strings",
		"conBonus": {"3":3,"2":5}
	},
	"Diluc": {
		"rarity": 5,
		"weapon": "Claymore",
		"region": "Mondstadt",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Everflame Seed",
		"local": "Small Lamp Grass",
		"common": "fatuiSkirmisher",
		"books": "Resistance",
		"weeklyBoss": "Dvalin's Plume",
		"conBonus": {"2":3,"3":5}
	},
	"Diona": {
		"rarity": 4,
		"weapon": "Bow",
		"region": "Mondstadt",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Hoarfrost Core",
		"local": "Calla Lily",
		"common": "hilichurlShooter",
		"books": "Freedom",
		"weeklyBoss": "Shard of a Foul Legacy",
		"conBonus": {"3":3,"2":5}
	},
	"Dori": {
		"rarity": 4,
		"weapon": "Claymore",
		"region": "Sumeru",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Thunderclap Fruitcore",
		"local": "Kalpalata Lotus",
		"common": "eremites",
		"books": "Ingenuity",
		"weeklyBoss": "Bloodjade Branch",
		"conBonus": {"3":3,"2":5}
	},
	"Eula": {
		"rarity": 5,
		"weapon": "Claymore",
		"region": "Mondstadt",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Crystalline Bloom",
		"local": "Dandelion Seed",
		"common": "hilichurl",
		"books": "Resistance",
		"weeklyBoss": "Dragon Lord's Crown",
		"conBonus": {"3":3,"2":5}
	},
	"Faruzan": {
		"rarity": 4,
		"weapon": "Bow",
		"region": "Sumeru",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": "Light Guiding Tetrahedron",
		"local": "Henna Berry",
		"common": "eremites",
		"books": "Admonition",
		"weeklyBoss": "Puppet Strings",
		"conBonus": {"2":3,"3":5}
	},
	"Fischl": {
		"rarity": 4,
		"weapon": "Bow",
		"region": "Mondstadt",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Lightning Prism",
		"local": "Small Lamp Grass",
		"common": "hilichurlShooter",
		"books": "Ballad",
		"weeklyBoss": "Spirit Locket of Boreas",
		"conBonus": {"2":3,"3":5}
	},
	"Freminet": {
		"rarity": 4,
		"weapon": "Claymore",
		"region": "Fontaine",
		"visionType": "Pneuma",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Artificed Spare Clockwork Component - Coppelius",
		"local": "Romaritime Flower",
		"common": "transoceanic",
		"books": "Justice",
		"weeklyBoss": "Worldspan Fern",
		"conBonus": {"1":3,"2":5}	
	},
	"Furina": {
		"rarity": 5,
		"weapon": "Sword",
		"vision": "Furina",
		"region": "Fontaine",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Water That Failed To Transcend",
		"local": "Lakelight Lily",
		"common": "whopperflower",
		"books": "Justice",
		"weeklyBoss": "Lightless Mass",
		"conBonus": {"2":3,"3":5}
	},
	"Gaming": {
		"include": false,
		"rarity": 4,
		"weapon": null,
		"region": "Liyue",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": null,
		"local": null,
		"common": null,
		"books": null,
		"weeklyBoss": null,
		"conBonus": null
	},
	"Ganyu": {
		"rarity": 5,
		"weapon": "Bow",
		"region": "Liyue",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Hoarfrost Core",
		"local": "Qingxin",
		"common": "whopperflower",
		"books": "Diligence",
		"weeklyBoss": "Shadow of the Warrior",
		"conBonus": {"3":3,"2":5}
	},
	"Gorou": {
		"rarity": 4,
		"weapon": "Bow",
		"region": "Inazuma",
		"type": "Geo",
		"gem": "Prithiva Topaz",
		"boss": "Perpetual Heart",
		"local": "Sango Pearl",
		"common": "specter",
		"books": "Light",
		"weeklyBoss": "Molten Moment",
		"conBonus": {"2":3,"3":5}
	},
	"Hu Tao": {
		"rarity": 5,
		"weapon": "Polearm",
		"region": "Liyue",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Juvenile Jade",
		"local": "Silk Flower",
		"common": "whopperflower",
		"books": "Diligence",
		"weeklyBoss": "Shard of a Foul Legacy",
		"conBonus": {"2":3,"3":5}
	},
	"Jean": {
		"rarity": 5,
		"weapon": "Sword",
		"region": "Mondstadt",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": "Hurricane Seed",
		"local": "Dandelion Seed",
		"common": "hilichurl",
		"books": "Resistance",
		"weeklyBoss": "Dvalin's Plume",
		"conBonus": {"3":3,"2":5}
	},
	"Kaedehara Kazuha": {
		"rarity": 5,
		"weapon": "Sword",
		"region": "Inazuma",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": "Marionette Core",
		"local": "Sea Ganoderma",
		"common": "treasureHoarder",
		"books": "Diligence",
		"weeklyBoss": "Gilded Scale",
		"conBonus": {"2":3,"3":5}
	},
	"Kaeya": {
		"rarity": 4,
		"weapon": "Sword",
		"region": "Mondstadt",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Hoarfrost Core",
		"local": "Calla Lily",
		"common": "treasureHoarder",
		"books": "Ballad",
		"weeklyBoss": "Spirit Locket of Boreas",
		"conBonus": {"2":3,"3":5}
	},
	"Kamisato Ayaka": {
		"rarity": 5,
		"weapon": "Sword",
		"region": "Inazuma",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Perpetual Heart",
		"local": "Sakura Bloom",
		"common": "nobushi",
		"books": "Elegance",
		"weeklyBoss": "Bloodjade Branch",
		"conBonus": {"3":3,"2":5}
	},
	"Kamisato Ayato": {
		"rarity": 5,
		"weapon": "Sword",
		"region": "Inazuma",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Dew of Repudiation",
		"local": "Sakura Bloom",
		"common": "nobushi",
		"books": "Elegance",
		"weeklyBoss": "Mudra of the Malefic General",
		"conBonus": {"2":3,"3":5}
	},
	"Kaveh": {
		"rarity": 4,
		"weapon": "Claymore",
		"region": "Sumeru",
		"type": "Dendro",
		"gem": "Nagadus Emerald",
		"boss": "Quelled Creeper",
		"local": "Mourning Flower",
		"common": "fungus",
		"books": "Ingenuity",
		"weeklyBoss": "Primordial Greenbloom",
		"conBonus": {"3":3,"2":5}
	},
	"Keqing": {
		"rarity": 5,
		"weapon": "Sword",
		"region": "Liyue",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Lightning Prism",
		"local": "Cor Lapis",
		"common": "whopperflower",
		"books": "Prosperity",
		"weeklyBoss": "Ring of Boreas",
		"conBonus": {"3":3,"2":5}
	},
	"Kirara": {
		"rarity": 4,
		"weapon": "Sword",
		"region": "Inazuma",
		"type": "Dendro",
		"gem": "Nagadus Emerald",
		"boss": "Evergloom Ring",
		"local": "Amakumo Fruit",
		"common": "specter",
		"books": "Transience",
		"weeklyBoss": "Everamber",
		"conBonus": {"2":3,"3":5}
	},
	"Klee": {
		"rarity": 5,
		"weapon": "Catalyst",
		"region": "Mondstadt",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Everflame Seed",
		"local": "Philanemo Mushroom",
		"common": "samachurl",
		"books": "Freedom",
		"weeklyBoss": "Ring of Boreas",
		"conBonus": {"2":3,"3":5}
	},
	"Kujou Sara": {
		"rarity": 4,
		"weapon": "Bow",
		"region": "Inazuma",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Storm Beads",
		"local": "Dendrobium",
		"common": "hilichurl",
		"books": "Elegance",
		"weeklyBoss": "Ashen Heart",
		"conBonus": {"3":3,"2":5}
	},
	"Kuki Shinobu": {
		"rarity": 4,
		"weapon": "Sword",
		"region": "Inazuma",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Runic Fang",
		"local": "Naku Weed",
		"common": "specter",
		"books": "Elegance",
		"weeklyBoss": "Tears of the Calamitous God",
		"conBonus": {"2":3,"3":5}
	},
	"Layla": {
		"rarity": 4,
		"weapon": "Sword",
		"region": "Sumeru",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Perpetual Caliber",
		"local": "Nilotpala Lotus",
		"common": "samachurl",
		"books": "Ingenuity",
		"weeklyBoss": "Mirror of Mushin",
		"conBonus": {"2":3,"3":5}
	},
	"Lisa": {
		"rarity": 4,
		"weapon": "Catalyst",
		"region": "Mondstadt",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Lightning Prism",
		"local": "Valberry",
		"common": "slime",
		"books": "Ballad",
		"weeklyBoss": "Dvalin's Claw",
		"conBonus": {"3":3,"2":5}
	},
	"Lynette": {
		"rarity": 4,
		"weapon": "Sword",
		"region": "Fontaine",
		"visionType": "Pneuma",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": "Artificed Spare Clockwork Component - Coppelia",
		"local": "Lumidouce Bell",
		"common": "clockworkMeka",
		"books": "Order",
		"weeklyBoss": "Everamber",
		"conBonus": {"3":3,"2":5}
	},
	"Lyney": {
		"rarity": 5,
		"weapon": "Bow",
		"region": "Fontaine",
		"visionType": "Ousia",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Emperor's Resolution",
		"local": "Rainbow Rose",
		"common": "fatuiSkirmisher",
		"books": "Equity",
		"weeklyBoss": "Primordial Greenbloom",
		"conBonus": {"1":3,"3":5}
	},
	"Mika": {
		"rarity": 4,
		"weapon": "Polearm",
		"region": "Mondstadt",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Pseudo-Stamens",
		"local": "Wolfhook",
		"common": "fatuiSkirmisher",
		"books": "Ballad",
		"weeklyBoss": "Mirror of Mushin",
		"conBonus": {"3":3,"2":5}
	},
	"Mona": {
		"rarity": 5,
		"weapon": "Catalyst",
		"region": "Mondstadt",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Cleansing Heart",
		"local": "Philanemo Mushroom",
		"common": "whopperflower",
		"books": "Resistance",
		"weeklyBoss": "Ring of Boreas",
		"conBonus": {"3":3,"2":5}
	},
	"Nahida": {
		"rarity": 5,
		"weapon": "Catalyst",
		"region": "Sumeru",
		"type": "Dendro",
		"gem": "Nagadus Emerald",
		"boss": "Quelled Creeper",
		"local": "Kalpalata Lotus",
		"common": "fungus",
		"books": "Ingenuity",
		"weeklyBoss": "Puppet Strings",
		"conBonus": {"2":3,"3":5}
	},
	"Navia": {
		"include": false,
		"rarity": 4,
		"weapon": "Claymore",
		"region": "Fontaine",
		"visionType": "Ousia",
		"type": "Geo",
		"gem": "Prithiva Topaz",
		"boss": "Artificed Spare Clockwork Component - Coppelius",
		"local": "Spring of the First Dewdrop",
		"common": "transoceanic",
		"books": "Equity",
		"weeklyBoss": "Lightless Silk String",
		"conBonus": null
	},
	"Neuvillette": {
		"rarity": 5,
		"weapon": "Catalyst",
		"region": "Fontaine",
		"visionType": "Pneuma",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Fontemer Unihorn",
		"local": "Lumitoile",
		"common": "transoceanic",
		"books": "Equity",
		"weeklyBoss": "Everamber",
		"conBonus": {"1":3,"3":5}
	},
	"Nilou": {
		"rarity": 5,
		"weapon": "Sword",
		"region": "Sumeru",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Perpetual Caliber",
		"local": "Padisarah",
		"common": "fungus",
		"books": "Praxis",
		"weeklyBoss": "Tears of the Calamitous God",
		"conBonus": {"3":3,"2":5}
	},
	"Ningguang": {
		"rarity": 4,
		"weapon": "Catalyst",
		"region": "Liyue",
		"type": "Geo",
		"gem": "Prithiva Topaz",
		"boss": "Basalt Pillar",
		"local": "Glaze Lily",
		"common": "fatuiSkirmisher",
		"books": "Prosperity",
		"weeklyBoss": "Spirit Locket of Boreas",
		"conBonus": {"3":3,"2":5}
	},
	"Noelle": {
		"rarity": 4,
		"weapon": "Claymore",
		"region": "Mondstadt",
		"type": "Geo",
		"gem": "Prithiva Topaz",
		"boss": "Basalt Pillar",
		"local": "Valberry",
		"common": "hilichurl",
		"books": "Resistance",
		"weeklyBoss": "Dvalin's Claw",
		"conBonus": {"2":3,"3":5}
	},
	"Qiqi": {
		"rarity": 5,
		"weapon": "Sword",
		"region": "Liyue",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Hoarfrost Core",
		"local": "Violetgrass",
		"common": "samachurl",
		"books": "Prosperity",
		"weeklyBoss": "Tail of Boreas",
		"conBonus": {"3":3,"2":5}
	},
	"Raiden Shogun": {
		"rarity": 5,
		"weapon": "Polearm",
		"region": "Inazuma",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Storm Beads",
		"local": "Amakumo Fruit",
		"common": "nobushi",
		"books": "Light",
		"weeklyBoss": "Molten Moment",
		"conBonus": {"3":3,"2":5}
	},
	"Razor": {
		"rarity": 4,
		"weapon": "Claymore",
		"region": "Mondstadt",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Lightning Prism",
		"local": "Wolfhook",
		"common": "hilichurl",
		"books": "Resistance",
		"weeklyBoss": "Dvalin's Claw",
		"conBonus": {"3":3,"2":5}
	},
	"Rosaria": {
		"rarity": 4,
		"weapon": "Polearm",
		"region": "Mondstadt",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Hoarfrost Core",
		"local": "Valberry",
		"common": "fatuiSkirmisher",
		"books": "Ballad",
		"weeklyBoss": "Shadow of the Warrior",
		"conBonus": {"2":3,"3":5}
	},
	"Sangonomiya Kokomi": {
		"rarity": 5,
		"weapon": "Catalyst",
		"region": "Inazuma",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Dew of Repudiation",
		"local": "Sango Pearl",
		"common": "specter",
		"books": "Transience",
		"weeklyBoss": "Hellfire Butterfly",
		"conBonus": {"3":3,"2":5}
	},
	"Sayu": {
		"rarity": 4,
		"weapon": "Claymore",
		"region": "Inazuma",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": "Marionette Core",
		"local": "Crystal Marrow",
		"common": "whopperflower",
		"books": "Light",
		"weeklyBoss": "Gilded Scale",
		"conBonus": {"3":3,"2":5}
	},
	"Shenhe": {
		"rarity": 5,
		"weapon": "Polearm",
		"region": "Liyue",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Dragonheir's False Fin",
		"local": "Qingxin",
		"common": "whopperflower",
		"books": "Prosperity",
		"weeklyBoss": "Hellfire Butterfly",
		"conBonus": {"2":3,"3":5}
	},
	"Shikanoin Heizou": {
		"rarity": 4,
		"weapon": "Catalyst",
		"region": "Inazuma",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": "Runic Fang",
		"local": "Onikabuto",
		"common": "treasureHoarder",
		"books": "Transience",
		"weeklyBoss": "The Meaning of Aeons",
		"conBonus": {"2":3,"3":5}
	},
	"Sigewinne": {
		"include": false,
		"rarity": 4,
		"weapon": null,
		"region": "Fontaine",
		"visionType": "Pneuma",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": null,
		"local": null,
		"common": null,
		"books": null,
		"weeklyBoss": null,
		"conBonus": null
	},
	"Sucrose": {
		"rarity": 4,
		"weapon": "Catalyst",
		"region": "Mondstadt",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": "Hurricane Seed",
		"local": "Windwheel Aster",
		"common": "whopperflower",
		"books": "Freedom",
		"weeklyBoss": "Spirit Locket of Boreas",
		"conBonus": {"2":3,"3":5}
	},
	"Tartaglia": {
		"rarity": 5,
		"weapon": "Bow",
		"region": "Snezhnaya",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Cleansing Heart",
		"local": "Starconch",
		"common": "fatuiSkirmisher",
		"books": "Freedom",
		"weeklyBoss": "Shard of a Foul Legacy",
		"conBonus": {"2":3,"3":5}
	},
	"Thoma": {
		"rarity": 4,
		"weapon": "Polearm",
		"region": "Inazuma",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Smoldering Pearl",
		"local": "Fluorescent Fungus",
		"common": "treasureHoarder",
		"books": "Transience",
		"weeklyBoss": "Hellfire Butterfly",
		"conBonus": {"2":3,"3":5}
	},
	"Tighnari": {
		"rarity": 5,
		"weapon": "Bow",
		"region": "Sumeru",
		"type": "Dendro",
		"gem": "Nagadus Emerald",
		"boss": "Majestic Hooked Beak",
		"local": "Nilotpala Lotus",
		"common": "fungus",
		"books": "Admonition",
		"weeklyBoss": "The Meaning of Aeons",
		"conBonus": {"3":3,"2":5}
	},
	"Venti": {
		"rarity": 5,
		"weapon": "Bow",
		"region": "Mondstadt",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": "Hurricane Seed",
		"local": "Cecilia",
		"common": "slime",
		"books": "Ballad",
		"weeklyBoss": "Tail of Boreas",
		"conBonus": {"3":3,"2":5}
	},
	"Wanderer": {
		"canRename": true,
		"rarity": 5,
		"weapon": "Catalyst",
		"region": "Sumeru",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": "Perpetual Caliber",
		"local": "Rukkhashava Mushrooms",
		"common": "nobushi",
		"books": "Praxis",
		"weeklyBoss": "Daka's Bell",
		"conBonus": {"3":3,"2":5}
	},
	"Wriothesley": {
		"rarity": 5,
		"weapon": "Catalyst",
		"region": "Fontaine",
		"visionType": "Ousia",
		"type": "Cryo",
		"gem": "Shivada Jade",
		"boss": "Tourbillon Device",
		"local": "Subdetection Unit",
		"common": "clockworkMeka",
		"books": "Order",
		"weeklyBoss": "Primordial Greenbloom",
		"conBonus": {"1":3,"3":5}
	},
	"Xiangling": {
		"rarity": 4,
		"weapon": "Polearm",
		"region": "Liyue",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Everflame Seed",
		"local": "Jueyun Chili",
		"common": "slime",
		"books": "Diligence",
		"weeklyBoss": "Dvalin's Claw",
		"conBonus": {"3":3,"2":5}
	},
	"Xianyun": {
		"include": false,
		"rarity": 5,
		"weapon": null,
		"region": "Liyue",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": null,
		"local": null,
		"common": null,
		"books": null,
		"weeklyBoss": null,
		"conBonus": null
	},
	"Xiao": {
		"rarity": 5,
		"weapon": "Polearm",
		"region": "Liyue",
		"type": "Anemo",
		"gem": "Vayuda Turquoise",
		"boss": "Juvenile Jade",
		"local": "Qingxin",
		"common": "slime",
		"books": "Prosperity",
		"weeklyBoss": "Shadow of the Warrior",
		"conBonus": {"2":3,"3":5}
	},
	"Xingqiu": {
		"rarity": 4,
		"weapon": "Sword",
		"region": "Liyue",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Cleansing Heart",
		"local": "Silk Flower",
		"common": "hilichurl",
		"books": "Gold",
		"weeklyBoss": "Tail of Boreas",
		"conBonus": {"3":3,"2":5}
	},
	"Xinyan": {
		"rarity": 4,
		"weapon": "Claymore",
		"region": "Liyue",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Everflame Seed",
		"local": "Violetgrass",
		"common": "treasureHoarder",
		"books": "Gold",
		"weeklyBoss": "Tusk of Monoceros Caeli",
		"conBonus": {"2":3,"3":5}
	},
	"Yae Miko": {
		"rarity": 5,
		"weapon": "Catalyst",
		"region": "Inazuma",
		"type": "Electro",
		"gem": "Vajrada Amethyst",
		"boss": "Dragonheir's False Fin",
		"local": "Sea Ganoderma",
		"common": "nobushi",
		"books": "Light",
		"weeklyBoss": "The Meaning of Aeons",
		"conBonus": {"2":3,"3":5}
	},
	"Yanfei": {
		"rarity": 4,
		"weapon": "Catalyst",
		"region": "Liyue",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Juvenile Jade",
		"local": "Noctilucous Jade",
		"common": "treasureHoarder",
		"books": "Gold",
		"weeklyBoss": "Bloodjade Branch",
		"conBonus": {"2":3,"3":5}
	},
	"Yaoyao": {
		"rarity": 4,
		"weapon": "Polearm",
		"region": "Liyue",
		"type": "Dendro",
		"gem": "Nagadus Emerald",
		"boss": "Quelled Creeper",
		"local": "Jueyun Chili",
		"common": "slime",
		"books": "Diligence",
		"weeklyBoss": "Daka's Bell",
		"conBonus": {"2":3,"3":5}
	},
	"Yelan": {
		"rarity": 5,
		"weapon": "Bow",
		"region": "Liyue",
		"type": "Hydro",
		"gem": "Varunada Lazurite",
		"boss": "Runic Fang",
		"local": "Starconch",
		"common": "fatuiSkirmisher",
		"books": "Prosperity",
		"weeklyBoss": "Gilded Scale",
		"conBonus": {"3":3,"2":5}
	},
	"Yoimiya": {
		"rarity": 5,
		"weapon": "Bow",
		"region": "Inazuma",
		"type": "Pyro",
		"gem": "Agnidus Agate",
		"boss": "Smoldering Pearl",
		"local": "Naku Weed",
		"common": "samachurl",
		"books": "Transience",
		"weeklyBoss": "Dragon Lord's Crown",
		"conBonus": {"2":3,"3":5}
	},
	"Yun Jin": {
		"rarity": 4,
		"weapon": "Polearm",
		"region": "Liyue",
		"type": "Geo",
		"gem": "Prithiva Topaz",
		"boss": "Riftborn Regalia",
		"local": "Glaze Lily",
		"common": "hilichurl",
		"books": "Diligence",
		"weeklyBoss": "Ashen Heart",
		"conBonus": {"3":3,"2":5}
	},
	"Zhongli": {
		"rarity": 5,
		"weapon": "Polearm",
		"region": "Liyue",
		"type": "Geo",
		"gem": "Prithiva Topaz",
		"boss": "Basalt Pillar",
		"local": "Cor Lapis",
		"common": "slime",
		"books": "Gold",
		"weeklyBoss": "Tusk of Monoceros Caeli",
		"conBonus": {"2":3,"3":5}
	},
	"Traveler": {
		"canRename": true,
		"region": null,
		"type": null,
		"rarity": 5,
		"weapon": "Sword",
		"gem": "Brilliant Diamond",
		"boss": null,
		"local": "Windwheel Aster",
		"common": "hilichurl",
		"weeklyBoss": null,
		"regions": [
			{
				"hasCons": false,
				"region": null,
				"type": "Unaligned",
				"books": ["Freedom", "Resistance", "Ballad"],
				"weeklyBoss": "Dvalin's Sigh",
				"common": "samachurl"
			},{
				"region": "Mondstadt",
				"type": "Anemo",
				"books": ["Freedom", "Resistance", "Ballad"],
				"weeklyBoss": "Dvalin's Sigh",
				"common": "samachurl",
				"conBonus": {"3":3,"2":5}
			},{
				"region": "Liyue",
				"type": "Geo",
				"books": ["Prosperity", "Diligence", "Gold"],
				"weeklyBoss": "Tail of Boreas",
				"common": "hilichurlShooter",
				"conBonus": {"3":3,"2":5}
			},{
				"region": "Inazuma",
				"type": "Electro",
				"books": ["Transience", "Elegance", "Light"],
				"weeklyBoss": "Dragon Lord's Crown",
				"common": "nobushi",
				"conBonus": {"3":3,"2":5}
			},{
				"region": "Sumeru",
				"type": "Dendro",
				"books": ["Admonition", "Ingenuity", "Praxis"],
				"weeklyBoss": "Mudra of the Malefic General",
				"common": "fungus",
				"conBonus": {"2":3,"3":5}
			},{
				"region": "Fontaine",
				"type": "Hydro",
				"books": ["Equity", "Justice", "Order"],
				"weeklyBoss": "Worldspan Fern",
				"common": "taintedWater",
				"conBonus": {"2":3,"3":5}
			},{
				"include": false,
				"region": "Natlan",
				"type": "Pyro",
				"books": null,
				"weeklyBoss": null,
				"common": null,
				"conBonus": null
			},{
				"include": false,
				"region": "Snezhnaya",
				"type": "Cryo",
				"books": null,
				"weeklyBoss": null,
				"common": null,
				"conBonus": null
			}
		]
	}
}
const charTypes = ["Pyro","Hydro","Electro","Cryo","Dendro","Anemo","Geo","Unaligned"];
const charRegions = [null,"Mondstadt","Liyue","Inazuma","Sumeru","Fontaine","Natlan","Snezhnaya","Khaenri'ah"];
const maxCon = 6;
const charMaxTalents = [10,10,10];
const charTalentSuffix = ["-tal1","-tal2","-tal3"];
const charTalentNames = ["Normal Attack", "Skill", "Burst"];
const allChars = [];
for (let i in chars) {allChars.push(i)}
const travTypeOrder = [];
const emptyByElement = [];
for (let i in chars["Traveler"].regions) {
	let r = chars["Traveler"].regions[i];
	if(r.include === false) {
		continue;
	}
	emptyByElement.push({});
	travTypeOrder.push(r.type);
}
